spring.application.name=gamestore

##Configurar o Banco de Dados
spring.datasource.url=jdbc:postgresql://dpg-d6tvgfn5gffc739duoh0-a:5432/db_deploy_gs_muski360
spring.datasource.username=db_deploy_gs_muski360
spring.datasource.password=HgvEJsXK2zSBXDfMSs9uc4VD99FpYVyC
# obs: nunca colocar senhas em documentos que vão para o github

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect 